const colors = {
  light: {
    text: "#F0EEFF",
    tint: "#7C3AED",
    background: "#0A0A12",
    foreground: "#F0EEFF",
    card: "#141426",
    cardForeground: "#F0EEFF",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#1E1E38",
    secondaryForeground: "#F0EEFF",
    muted: "#1E1E38",
    mutedForeground: "#8888AA",
    accent: "#F59E0B",
    accentForeground: "#000000",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A4A",
    input: "#1E1E38",
  },
  dark: {
    text: "#F0EEFF",
    tint: "#7C3AED",
    background: "#0A0A12",
    foreground: "#F0EEFF",
    card: "#141426",
    cardForeground: "#F0EEFF",
    primary: "#7C3AED",
    primaryForeground: "#FFFFFF",
    secondary: "#1E1E38",
    secondaryForeground: "#F0EEFF",
    muted: "#1E1E38",
    mutedForeground: "#8888AA",
    accent: "#F59E0B",
    accentForeground: "#000000",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A4A",
    input: "#1E1E38",
  },
  radius: 16,
};

export default colors;
